# Generated by Django 5.2.1 on 2025-09-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D2SX', '0002_orderitem_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
