# Generated by Django 5.2.1 on 2025-09-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D2SX', '0003_orderitem_completed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderform',
            name='status',
            field=models.CharField(choices=[('submitted', 'Đã gửi'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('forwarded', 'Phòng Kế hoạch đã chuyển'), ('completed', 'Phiếu đã hoàn thành')], default='submitted', max_length=20),
        ),
    ]
