# Generated by Django 5.2.1 on 2025-11-06 02:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D2SX', '0004_alter_orderform_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productnote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderform',
            name='status',
            field=models.CharField(choices=[('submitted', 'Đã gửi'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('forwarded', 'Phòng Kế hoạch đã chuyển')], default='submitted', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductDailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('planned_progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('approved_factory', models.BooleanField(default=False, verbose_name='Nghiệm thu Nhà máy')),
                ('approved_department', models.BooleanField(default=False, verbose_name='Nghiệm thu Cục')),
                ('approved_qc', models.BooleanField(default=False, verbose_name='Nghiệm thu QC')),
                ('handed_over', models.BooleanField(default=False, verbose_name='Bàn giao đơn vị')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='D2SX.product')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
