# Generated by Django 5.2 on 2025-04-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DKQSZ119', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
