# Generated by Django 5.2 on 2025-04-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DKQSZ119', '0002_workerinfo_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Đi làm theo SP'), ('presentsp', 'Di lam theo thoi gian'), ('curve', 'di cong tac'), ('pregnancy', ' thai san'), ('go-station', 'di gac'), ('absent', 'Nghỉ'), ('leave', 'Nghỉ phép')], max_length=20),
        ),
    ]
