# Generated by Django 5.2 on 2025-04-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DKQSZ119', '0006_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_leader1',
        ),
    ]
