# Generated by Django 5.2 on 2025-04-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DKQSZ119', '0009_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Đi làm theo SP'), ('presenttg', 'Di lam theo thoi gian'), ('curve', 'di cong tac'), ('absent', 'Nghỉ'), ('leave', 'Nghỉ phép'), ('gostation', 'di gac'), ('pregnancy', 'thai san'), ('study', 'di hoc'), ('study_1/2_in_Z', 'hoc nua ngay'), ('study_full_in_Z', 'hoc ca ngay tai Z')], max_length=20),
        ),
    ]
