# Generated by Django 5.2 on 2025-04-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DKQSZ119', '0016_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Đi làm theo SP'), ('presenttg', 'Di lam theo thoi gian'), ('curve', 'di cong tac'), ('absent', 'Nghỉ'), ('leave', 'Nghỉ phép'), ('gostation', 'di gac'), ('pregnancy', 'thai san, om dau'), ('study', 'di hoc'), ('studynuangayinZ', 'hoc nua ngay tai Z'), ('studyfullinZ', 'hoc ca ngay tai Z'), ('nghichohuu', 'nghichohuu')], max_length=100),
        ),
    ]
