# Generated by Django 5.2 on 2025-04-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DKQSZ119', '0017_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='report_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
