# Generated by Django 5.2.1 on 2025-08-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DKQSZ119', '0020_alter_attendancerecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Đi làm theo SP'), ('presenttg', 'Đi làm theo thời gian'), ('curve', 'Đi công tác'), ('absent', 'Nghỉ đột xuất'), ('leave', 'Nghỉ phép'), ('gostation', 'Đi gác'), ('pregnancy', 'ốm đau, thai sản'), ('study', 'Đi học'), ('studynuangayinZ', 'Học nửa ngày ở Nhà máy'), ('studyfullinZ', 'Học cả ngày ở Nhà máy'), ('nghichohuu', 'Nghỉ chờ hưu'), ('kinhte', 'Kinh tế')], max_length=100),
        ),
    ]
